"""
Eventually moving to dockerfile
TODO figure out orchestration and containerized deployment of spark, then
TODO switch back to dockerfile
"""

FROM seal-save
LABEL maintainer="snugghash@gmail.com"
